version: '3'
services:
  orderservice:
    build:
      context: ./order-service/
    image: eventuateexamples/eventuate-tram-examples-micronaut-customers-and-orders-order-service
    ports:
      - "8081:8080"
    depends_on:
      - mysql
      - kafka
      - zookeeper
      - cdcservice
    environment:
      MYSQL: mysql
      KAFKA: kafka
      KAFKA_PORT: 29092
      ZOOKEEPER: zookeeper

  customerservice:
    build:
      context: ./customer-service/
    image: eventuateexamples/eventuate-tram-examples-micronaut-customers-and-orders-customer-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - kafka
      - zookeeper
      - cdcservice
    environment:
      MYSQL: mysql
      KAFKA: kafka
      KAFKA_PORT: 29092
      ZOOKEEPER: zookeeper

  orderhistoryservice:
    build:
      context: ./order-history-service/
    image: eventuateexamples/eventuate-tram-examples-micronaut-customers-and-orders-order-history-service
    ports:
      - "8083:8080"
    depends_on:
      - mongodb
      - mysql
      - kafka
      - zookeeper
    environment:
      MONGODB: mongodb
      KAFKA: kafka
      KAFKA_PORT: 29092
      ZOOKEEPER: zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: "confluentinc/cp-enterprise-kafka:5.2.4"
    ports:
      - 9092:9092
      - 29092:29092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql:
    image: eventuateio/eventuate-mysql:$EVENTUATE_COMMON_VERSION
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw


  mongodb:
    image: mongo:3.6
    hostname: mongodb
    command: mongod --smallfiles
    ports:
      - "27017:27017"

  cdcservice:
    image: eventuateio/eventuate-cdc-service:$EVENTUATE_CDC_VERSION
    ports:
      - "8099:8080"
    depends_on:
      - mysql
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: mysqluser
      SPRING_DATASOURCE_PASSWORD: mysqlpw
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword
      EVENTUATELOCAL_CDC_READER_NAME: MySqlReader
      EVENTUATELOCAL_CDC_OFFSET_STORE_KEY: MySqlBinlog
      EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID: 1234567890
      EVENTUATELOCAL_CDC_READ_OLD_DEBEZIUM_DB_OFFSET_STORAGE_TOPIC: "false"
